# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './数据字典同步.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QButtonGroup


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(832, 605)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 801, 31))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 40, 801, 41))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.fromButton2 = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.fromButton2.setObjectName("fromButton2")
        self.gridLayout_3.addWidget(self.fromButton2, 0, 2, 1, 1)
        self.fromButton1 = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.fromButton1.setChecked(True)
        self.fromButton1.setObjectName("fromButton1")
        self.gridLayout_3.addWidget(self.fromButton1, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.fromButton3 = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.fromButton3.setObjectName("fromButton3")
        self.gridLayout_3.addWidget(self.fromButton3, 0, 3, 1, 1)
        self.bg1 = QButtonGroup()
        self.bg1.addButton(self.fromButton1, 11)
        self.bg1.addButton(self.fromButton2, 21)
        self.bg1.addButton(self.fromButton3, 31)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 80, 801, 91))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.toButton1 = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        self.toButton1.setObjectName("toButton1")
        self.gridLayout_2.addWidget(self.toButton1, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.toButton2 = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        self.toButton2.setChecked(True)
        self.toButton2.setObjectName("toButton2")
        self.gridLayout_2.addWidget(self.toButton2, 0, 2, 1, 1)
        self.toButton3 = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        self.toButton3.setObjectName("toButton3")
        self.gridLayout_2.addWidget(self.toButton3, 0, 3, 1, 1)
        self.bg2 = QButtonGroup()
        self.bg2.addButton(self.toButton1, 11)
        self.bg2.addButton(self.toButton2, 21)
        self.bg2.addButton(self.toButton3, 31)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 2)
        self.saveCaidan = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.saveCaidan.setObjectName("saveCaidan")
        self.gridLayout_4.addWidget(self.saveCaidan, 1, 0, 1, 2)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(20, 270, 801, 281))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 170, 801, 381))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 832, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "UMS表结构新增和变更功能"))
        self.fromButton2.setText(_translate("MainWindow", "预上线"))
        self.fromButton1.setText(_translate("MainWindow", "测试"))
        self.label_2.setText(_translate("MainWindow", "请选择同步源："))
        self.fromButton3.setText(_translate("MainWindow", "正式"))
        self.toButton1.setText(_translate("MainWindow", "测试"))
        self.label_4.setText(_translate("MainWindow", "请选择目标库："))
        self.toButton2.setText(_translate("MainWindow", "预上线"))
        self.toButton3.setText(_translate("MainWindow", "正式"))
        self.saveCaidan.setText(_translate("MainWindow", "保存同步sql"))
